spring:
  profiles:
    active: test
    include:
      - oauth

  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  session:
    store-type: jdbc

---

spring:
  profiles: real
  include:
    - real-db

---

spring:
  profiles: test

  h2:
    console:
      enabled: true
