spring:
  profiles:
    active: prod

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb

  session:
    store-type: jdbc

---
spring:
  profiles:
    group:
      "local": "testdb,oauth"
---
spring:
  profiles:
    group:
      "dev": "testdb,oauth"
---
spring:
  profiles:
    group:
      "prod": "proddb,oauth"
---
spring:
  config:
    activate:
      on-profile: "testdb"

  h2:
    console:
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
      driver-class-name: org.h2.Driver
---
spring:
  config:
    activate:
      on-profile: "proddb"

  jpa:
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
  prod:
    datasource:
      hikari:
        jdbc-url: jdbc:mariadb://webservice.cbrmosdukjmp.ap-northeast-2.rds.amazonaws.com/webservice?zeroDateTimeBehavior=convertToNull&characterEncoding=UTF8&useUnicode=true
        driver-class-name: org.mariadb.jdbc.Driver


