spring:
  profiles:
    active: prod

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        storage_engine: innodb

  session:
    store-type: jdbc

  security:
    oauth2:
      client:
        registration:

          # google
          google:
            scope: profile, email

          # naver
          naver:
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            authorization_grant_type: authorization_code
            scope: name, email, profile_image
            client-name: Naver

        # provider
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nidnaver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
---
spring:
  profiles:
    group:
      "local": "testdb"
---
spring:
  profiles:
    group:
      "dev": "testdb"
---
spring:
  profiles:
    group:
      "prod": "proddb"
---
spring:
  config:
    activate:
      on-profile: "testdb"

  h2:
    console:
      enabled: true

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL
      username: sa
      driver-class-name: org.h2.Driver
---
spring:
  config:
    activate:
      on-profile: "proddb"

  jpa:
    hibernate:
      ddl-auto: none
  prod:
    datasource:
      hikari:
        jdbc-url: jdbc:mariadb://webservice.cbrmosdukjmp.ap-northeast-2.rds.amazonaws.com:3306/webservice
        driver-class-name: org.mariadb.jdbc.Driver


